before_install:
  - npm i -g npm
language: node_js # Sets which engine use to build the project  
node_js: "node" # Specifies node version to use "node"="latest"
services: mongodb
notifications:
    slack: devopsp-la:EhPAZGAvCJaO3KuCXLvZlMz2
